/**
 * Zero-dependency bundler: ES modules -> one classic browser script.
 *
 * Why: browsers block `import` of local files over the file:// protocol (a CORS
 * restriction), so a module-based app appears to "do nothing" when index.html
 * is opened by double-clicking. A classic (non-module) script has no such
 * restriction, so bundling makes EcoTrack work both when opened directly AND
 * when served — with no runtime dependencies and no real build tooling.
 *
 * The ES modules remain the single source of truth (the test suite imports them
 * directly). This script just concatenates them into a tiny CommonJS-style
 * runtime that preserves per-module scope (so identically named helpers like
 * `round()` in different files never collide).
 *
 * Run with: npm run build
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, normalize } from 'node:path';

const ROOT = normalize(join(dirname(fileURLToPath(import.meta.url)), '..'));

// Every browser module, keyed by its path under src/ (without extension).
const MODULES = [
  'data/emissionFactors',
  'core/format',
  'core/calculator',
  'core/benchmarks',
  'core/planner',
  'core/recommendations',
  'core/insights',
  'core/storage',
  'chart',
  'presets',
  'app', // entry point, required last
];

/** Resolve a relative import specifier to a module key. */
function resolveKey(fromKey, specifier) {
  const fromDir = dirname(`${fromKey}.js`);
  const target = normalize(join(fromDir, specifier)).replace(/\\/g, '/');
  return target.replace(/\.js$/, '');
}

/** Transform one ES module's source into a CommonJS factory body. */
function transform(key, source) {
  const exported = [];

  // Collect exported binding names before we strip the keyword.
  const exportRe = /export\s+(?:const|let|var|function|class)\s+([A-Za-z0-9_$]+)/g;
  for (const m of source.matchAll(exportRe)) exported.push(m[1]);

  let body = source
    // Rewrite `import { a, b as c } from './x.js'` -> destructure from require.
    .replace(
      /import\s+\{([\s\S]*?)\}\s+from\s+['"]([^'"]+)['"];?/g,
      (_match, names, spec) => {
        const destructured = names
          .split(',')
          .map((n) => n.trim())
          .filter(Boolean)
          .map((n) => n.replace(/\s+as\s+/, ': '))
          .join(', ');
        return `const { ${destructured} } = __require('${resolveKey(key, spec)}');`;
      },
    )
    // Drop the `export ` keyword; the bindings are collected separately.
    .replace(/export\s+(const|let|var|function|class)\b/g, '$1');

  if (exported.length) {
    body += `\n  module.exports = { ${exported.join(', ')} };\n`;
  }

  return `__def(${JSON.stringify(key)}, function (module, __require) {\n${body}\n});`;
}

function build() {
  const factories = MODULES.map((key) => {
    const source = readFileSync(join(ROOT, 'src', `${key}.js`), 'utf8');
    return transform(key, source);
  });

  const out = `/* EcoTrack bundle — GENERATED by scripts/build.js. Do not edit by hand.
 * Source of truth: the ES modules in src/. Rebuild with: npm run build
 * This classic script runs from file:// as well as over http(s). */
(function () {
  'use strict';
  var __cache = {};
  var __factories = {};
  function __def(name, factory) { __factories[name] = factory; }
  function __require(name) {
    if (__cache[name]) return __cache[name].exports;
    var module = { exports: {} };
    __cache[name] = module;
    __factories[name](module, __require);
    return module.exports;
  }

${factories.join('\n\n')}

  __require('app');
})();
`;

  writeFileSync(join(ROOT, 'app.bundle.js'), out);
  console.log(`Built app.bundle.js (${MODULES.length} modules, ${out.length} bytes)`);
}

build();
